edition = "2018"

unstable_features = true

error_on_line_overflow = true
error_on_unformatted = true
report_fixme = "Unnumbered"
report_todo = "Always"

format_strings = true

max_width = 110

normalize_doc_attributes = true
normalize_comments = true
comment_width = 70
wrap_comments = true

condense_wildcard_suffixes = true

fn_single_line = true
fn_args_layout = "Vertical"

format_macro_matchers = true
hard_tabs = true

imports_layout = "HorizontalVertical"
imports_granularity = "Module"
group_imports = "StdExternalCrate"

inline_attribute_width = 60

match_arm_blocks = false
match_block_trailing_comma = true

newline_style = "Unix"

overflow_delimited_expr = true

reorder_impl_items = true

use_field_init_shorthand = true

use_try_shorthand = true
